name: Promote Staging Image to Production

on:
  push:
    branches:
      - 'main'

jobs:
  promote-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract image digest
        run: |
          export IMAGE_TAG=ghcr.io/${{ github.repository }}/${{ vars.PRODUCT_NAME }}:latest-rc
          export IMAGE_DIGEST=$(skopeo inspect docker://${IMAGE_TAG} | jq -r '.Digest')
          echo "IMAGE_DIGEST=$IMAGE_DIGEST" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add latest tag
        run: |
          export REPO=ghcr.io/${{ github.repository }}/${{ vars.PRODUCT_NAME }}
          echo "Promoting image $REPO@${IMAGE_DIGEST} to $REPO:latest"
          skopeo copy docker://${REPO}@${IMAGE_DIGEST} docker://${REPO}:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}