name: Promote Staging Image to Production

on:
  push:
    branches:
      - 'main'

jobs:
  promote-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get repo name
        id: get_lower_repo
        run: echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest-rc image
        run: |
          docker pull ghcr.io/${{ env.REPO }}/${{ vars.PRODUCT_NAME }}:latest-rc

      - name: Tag image as latest
        run: |
          docker tag ghcr.io/${{ env.REPO }}/${{ vars.PRODUCT_NAME }}:latest-rc \
                     ghcr.io/${{ env.REPO }}/${{ vars.PRODUCT_NAME }}:latest

      - name: Push image as latest
        run: |
          docker push ghcr.io/${{ env.REPO }}/${{ vars.PRODUCT_NAME }}:latest
