name: Promote Staging Image to Production

on:
  push:
    branches:
      - 'main'

env:
  PRODUCT_NAME: aem

jobs:
  promote-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Get repo name
        run: echo "REPO=${GITHUB_REPOSITORY@L}" >> "$GITHUB_ENV"

      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Retag image latest-rc -> latest (server-side copy)
        env:
          SRC_IMAGE: ghcr.io/${{ github.repository }}/aem:latest-rc
          DEST_IMAGE: ghcr.io/${{ github.repository }}/aem:latest
        run: |
          skopeo copy \
            --src-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
            --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
            docker://${SRC_IMAGE} \
            docker://${DEST_IMAGE}
