name: Sync staging with main

on:
  push:
    branches:
      - main

jobs:
  sync-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: staging

    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch all branches
      run: git fetch origin

    - name: Merge main into staging
      run: |
        git checkout staging
        git merge origin/main -m "Automated merge of main into staging [skip ci]"
        git push origin staging