name: Build and deploy Staging
on:
  push:
    branches: 
      - 'staging'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')" # Required since staging-sync creates a commit which we don't want to run the build with as it's unnecessary 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get repo name
        id: get_lower_repo
        run: echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

      - name: Set short GITHUB_SHA
        id: set_sha
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> "${GITHUB_ENV}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}/${{ vars.PRODUCT_NAME }}:latest-rc
            ghcr.io/${{ env.REPO }}/${{ vars.PRODUCT_NAME }}:${{ vars.VERSION }}-${{ env.SHORT_SHA }}
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker Compose
        run: |
          export DB_USER=${{ vars.DB_USER }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_PORT=${{ vars.DB_PORT }}
          export DB_NAME=${{ vars.DB_NAME }}
          export APP_PORT=${{ vars.APP_PORT }}
          export APP_IMAGAE=${{ vars.APP_IMAGE }}
          export API_TOKEN=${{ vars.API_TOKEN }}
          docker compose up -d 